version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cleanwhale-db
    environment:
      POSTGRES_DB: cleanwhale_analytics
      POSTGRES_USER: cleanwhale_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_this_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cleanwhale_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cleanwhale-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://cleanwhale_user:${POSTGRES_PASSWORD:-change_this_password}@postgres:5432/cleanwhale_analytics
      JWT_SECRET: ${JWT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  # Nginx reverse proxy (опционально, для SSL)
  nginx:
    image: nginx:alpine
    container_name: cleanwhale-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: always

volumes:
  postgres_data:




