#!/bin/bash

echo "🔧 ИСПРАВЛЕНИЕ DATABASE_URL для совместимости с PgBouncer"
echo ""
echo "📋 Инструкция:"
echo ""
echo "1. Зайди на: https://vercel.com"
echo "2. Открой проект: cleanwhale-hr-analytics"
echo "3. Settings → Environment Variables"
echo "4. Найди DATABASE_URL → нажми три точки → Edit"
echo ""
echo "5. Замени значение на:"
echo ""
echo "postgresql://postgres.msluhxhvayzgxfioxgdi:zYjbam-hahheh-mawmo2@aws-1-eu-central-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connect_timeout=30&statement_cache_size=0"
echo ""
echo "   ⚠️ ВАЖНО: Добавлено &statement_cache_size=0 в конце!"
echo ""
echo "6. Выбери: ✅ Production ✅ Preview ✅ Development"
echo "7. Нажми Save"
echo ""
echo "8. Вернись на главную страницу проекта"
echo "9. Нажми три точки → Redeploy → Deploy"
echo ""
echo "✅ После этого логин заработает!"
echo ""
echo "💡 Причина проблемы: PgBouncer не поддерживает prepared statements."
echo "   Параметр statement_cache_size=0 отключает их для совместимости."

